name: MERN CI Pipeline

# This tells GitHub to run the pipeline every time you push to the main branch
on:
  push:
    branches: [ "2.0", "master" ]
  pull_request:
    branches: [ "2.0", "master" ]

jobs:
  # JOB 1: Test the Frontend
  check-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Matching your Dockerfile version
        
    - name: Install Dependencies
      run: npm install
      
    - name: Verify React Build
      # This ensures your Vite config is valid and the code compiles!
      run: npm run build 

  # JOB 2: Test the Backend
  check-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install Dependencies
      # This catches any missing packages in your package.json
      run: npm install